trigger:
- main

pool:

- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlrm552558'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest